[tools]
"aqua:Kampfkarren/selene" = "latest"
cue = "latest"
go = "1.24"
"go:golang.org/x/tools/cmd/goimports" = "latest"
golangci-lint = "2"
prek = "0.3"
stylua = "latest"
yamllint = "latest"

[hooks]
enter = "prek install"
