local rpack = require("rpack.v1")
local values = rpack.values()

-- Render a script and ship it as executable. `executable = true` declares the
-- output's executable intent (the owner-execute bit, like git); read/write
-- bits follow the destination's local creation policy (umask), not the script.
local script = rpack.template(
    [[#!/bin/sh
echo "Hello from {{.name}}"
]],
    { name = values.name }
)
rpack.write("./hello.sh", script, { executable = true })

-- Compatibility alias: `{ mode = "755" }` means the same as
-- `{ executable = true }` ("644" means non-executable). It is an intent
-- alias, not a literal chmod — exact modes like "600" are rejected.
-- A write resets intent to non-executable, so declare with the final
-- write, or `rpack.chmod(path, "755")` after it.
rpack.write("./goodbye.sh", "#!/bin/sh\necho bye\n", { mode = "755" })

-- Files without a declared intent are non-executable.
rpack.write("./README_OUTPUT.txt", "generated by executable_script example\n")
