local rpack = require("rpack.v1")
local values = rpack.values()

-- Render a script and ship it executable. The `mode` option applies the
-- permission bits after the write (octal string, like chmod).
local script = rpack.template(
    [[#!/bin/sh
echo "Hello from {{.name}}"
]],
    { name = values.name }
)
rpack.write("./hello.sh", script, { mode = "755" })

-- Equivalent explicit form: write first, then amend the mode.
-- NOTE: chmod amends the current staged file only — a later write to the
-- same path resets the mode to 644, so always chmod after your last write.
rpack.write("./goodbye.sh", "#!/bin/sh\necho bye\n")
rpack.chmod("./goodbye.sh", "755")

-- Files without a declared mode land at the canonical default 644.
rpack.write("./README_OUTPUT.txt", "generated by executable_script example\n")
